app: main.c darray.c
	gcc -std=c11 -Wall -Werror -pedantic -Wconversion main.c darray.c -o app

ex: newton_example.c darray.c
	gcc -std=c11 -Wall -Werror -pedantic -Wconversion newton_example.c darray.c -o ex

d: darray.c
	gcc -std=c11 -Wall -Werror -pedantic -Wconversion darray.c -o d